import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { TRPCReactProvider } from '~/trpc/react';

import type { ReactNode } from 'react';
import '@repo/ui/globals.css';
import { Navbar } from '~/components';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html
      className={GeistSans.variable}
      lang='en'
    >
      <body>
        <TRPCReactProvider>
          <NuqsAdapter>
            <Navbar />
            {children}
          </NuqsAdapter>
        </TRPCReactProvider>
      </body>
    </html>
  );
};

export default RootLayout;
