[package]
name = "sag_128"
type = "bin"
authors = ["Vedant Chainani <vedant@zkpersona.xyz>"]

[dependencies]
noir_ring_signatures = { tag = "v0.1.0", git = "https://github.com/zkpersona/noir-ring-signatures", directory = "lib" }
